#!/bin/bash

BATTERY=0
URGENT_VALUE=35
CRITICAL_VALUE=20
desired_length=20


BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')
BATTERY_TIME=$(echo "${BATTERY_INFO}" | grep "remaining" | awk '{print $5}' | cut -d':' -f1,2)
BATTERY_CHARGE_RATE=$(echo $(( $(cat /sys/class/power_supply/BAT0/current_now) * $(cat /sys/class/power_supply/BAT0/voltage_now) / 1000000 / 1000000 )))


if [[ -n "$BATTERY_INFO" ]]; then 
    if [[ "${BATTERY_STATE}" = "Charging" ]]; then
        output=" ${BATTERY_POWER}%+ ${BATTERY_CHARGE_RATE}W"

    elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
        output=" ${BATTERY_POWER}%- ${BATTERY_TIME}"

        if [[ $BATTERY_POWER -le $CRITICAL_VALUE ]]; then
            output="%{F#ff0000} ${BATTERY_POWER}%-%{F-} ${BATTERY_TIME}"
        elif [[ $BATTERY_POWER -le $URGENT_VALUE ]]; then
            output="%{F#ffa000} ${BATTERY_POWER}%-%{F-} ${BATTERY_TIME}"
        fi
    else
        output=" ${BATTERY_POWER}%"
    fi
else
    output="No Battery"
fi

echo "${output}"