#!/bin/bash


brightness=$(cat /sys/class/backlight/*/brightness)
max_brightness=$(cat /sys/class/backlight/*/max_brightness)
percent=$(( "$brightness * 100 / $max_brightness" ))

if [[ ${percent} -lt 10 ]]; then
    echo " min"
elif [[ ${percent} -eq 100 ]]; then
    echo " max"
else
    echo " ${percent}%"
fi
