#!/bin/env python

import psutil
import time

def get_core_temperatures():
    # Получаем информацию о температурах для каждого ядра
    temps = psutil.sensors_temperatures().get('coretemp', [])
    perf_cores = [0, 4, 8, 12]
    eff_cores = [20, 21, 22, 23]

    # Расчет средней температуры
    avg_perf_temp = sum(core.current for core in temps if int(core.label[-2:]) in perf_cores and "Core" in core.label) / len(perf_cores)
    avg_eff_temp = sum(core.current for core in temps if int(core.label[-2:]) in eff_cores) / len(eff_cores)
    max_temp = int(temps[0].current)

    return max_temp, avg_perf_temp, avg_eff_temp

def main():
    max_temp, avg_perf_temp, avg_eff_temp = get_core_temperatures()
    if max_temp >= 70:
        color = "%{F#FF0000}"
    else:
        color = ""
    print(f"{color}{max_temp}{'%{F-}'}|{round(avg_perf_temp)}/{round(avg_eff_temp)}°C")


if __name__ == "__main__":
    while True:
        main()
        time.sleep(1)
