#!/bin/bash

memtotal=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
memavail=$(awk '/MemAvailable/ {print $2}' /proc/meminfo)
free_memory_percent=$(bc<<<"scale=2;($memtotal - $memavail) /1024 /1024")

format_output() {
  desired_length=5
    local text="$1"
    local text_length=${#text}
    if [ $text_length -lt $desired_length ]; then
        local total_padding=$((desired_length - text_length))
        printf "%s%${total_padding}s\n" "$text" ""
    else
        echo "$text"
    fi
}

output="󰍛 $free_memory_percent GiB"

format_output "$output"
