#!/bin/bash

statusLine=$(amixer get Capture | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk '{print $5}' | tr -d '[]%')
prefix="󰍬"


if [[ $volume -ge 100 ]]; then
    text="max"

elif [[ $volume -eq 0 ]]; then 
    text="off"

elif [[ $volume -lt 10 ]]; then
    text="min"

else
    text="${volume}%"

fi


if [[ -z "${status}" ]]; then
    text="%{F#757575}$text%{F-}"
    prefix="󰍭"
fi

echo "$prefix $text"
