#!/bin/bash

status=$(dunstctl get-pause-level)

if [[ "$1" -eq 1 ]]; then
    ~/.config/i3/scripts/notifier
elif [[ "$1" -eq 2 ]]; then
    dunstctl history-pop
fi

if [[ $status -eq "0" ]]; then
    echo " "
else
    echo " "
fi
