#!/bin/sh

PLAYER="chromium"
len=13

is_playing() {
    if playerctl --player=$PLAYER status 2>&1 | grep Playing > /dev/null; then
        return 0
    else
        return 1
    fi
}

is_paused() {
    if playerctl --player=$PLAYER status 2>&1 | grep Paused > /dev/null; then
        return 0
    else
        return 1
    fi
}

play_pause() {
    if is_playing; then
        echo "%{F#dec800}%{F-}"
    elif is_paused; then
        echo "%{F#dec800}%{F-}"
    else
    	echo ""
    fi
}

case $1 in
  previous)
    is_playing && playerctl --player=$PLAYER previous
    ;;
  next)
    is_playing && playerctl --player=$PLAYER next
    ;;
  play-pause)
    (is_paused || is_playing) && playerctl --player=$PLAYER play-pause && play_pause
    ;;
  title)
    if is_playing || is_paused; then
        text="$(playerctl --player="$PLAYER" metadata --format '{{ artist }}: {{ title }}')"
    else
        text="YoutubeMusic"
    fi
    printf "%-${len}.${len}s" "$text"
    ;;
  play_pause)
    play_pause
    ;;
esac
