#!/bin/env python

import requests
import os


def response(city: str) -> dict:
    URL = f"http://api.weatherapi.com/v1/current.json?key=a4900ab676174aa59ae91816242710&q={city}"
    req = requests.get(url=URL).json()

    temp = req['current']['temp_c']
    temp_feel = req['current']['feelslike_c']
    city = req['location']['name']
    condition = req['current']['condition']['text']
    humidity = req['current']['humidity']
    time = req['location']['localtime']

    return {'temp': temp,
            'temp_f': temp_feel,
            'city': city,
            'condition': condition,
            'humidity': humidity,
            'time': time
            }

def formatter(temp:str,
    temp_f:str,
    city:str,
    condition:str,
    humidity:str,
    time:str) -> str:

    text = f"{time}\ncity: {city}\ntemp: {temp}({temp_f})\ncondition: {condition}\nhumidity: {humidity}%"
    return text


def main(): 
    req = response(city="Voronezh")

    text = formatter(temp=req['temp'], temp_f=req['temp_f'], city=req['city'], condition=req['condition'], humidity=req['humidity'], time=req['time'])

    os.system(f"notify-send --app-name weather '{text}' --expire-time 20000")

if __name__ == "__main__":
    main()
