#!/bin/bash

if [[ "$1" -eq 1 ]]; then
    amixer -q sset Master "$2"%+ > /dev/null
elif [[ "$1" -eq 0 ]]; then
    amixer -q sset Master toggle > /dev/null
elif [[ "$1" -eq -1 ]]; then
    amixer -q sset Master "$2"%- > /dev/null
fi

