#!/bin/bash

step="2"


if [[ "$1" -eq 1 ]]; then 
    brightnessctl --class=backlight s "$step"%+ > /dev/null
elif [[ "$1" -eq -1 ]]; then 
    brightnessctl --class=backlight s "$step"%- > /dev/null
fi
