#!/usr/bin/env python3
# encoding:utf8

import os
import subprocess


def is_wireguard_running() -> bool:
	result = subprocess.run(['sudo', 'wg', 'show'], capture_output=True, text=True)
	try:
		if result.stdout != "":
			return True
		else:
			return False
	except:
		print(f"Ошибка: {result.stderr.strip()}")
		return False


def get_wireguard_interface() -> list[str]:
	result = subprocess.run(['sudo', 'wg', 'show'], capture_output=True, text=True)

	if result.returncode == 0:

		interface_name = ""
		interfaces:list[str] = []

		for line in result.stdout.splitlines():

			if line.startswith('interface:'):
				interface_name = line.split(': ')[1]
				if interface_name not in interfaces:
					interfaces.append(interface_name)

		return interfaces


def main():
	directory = '/home/ivanika/.config/WGfaces/'
	files = list(os.listdir(directory))

	conf_files = {index: file for index, file in enumerate(files) if ".conf" in file}
	list_num_files = [index for index in conf_files.keys()]

	fl = input("Disable? [N/y] ")

	if fl.lower() == "n" or fl == "":

		print("")
		for index, file in conf_files.items():
			print(f"{index}: {file}")

		print("")
		selected_index = input("Выберите файл из списка по номеру: ")

		try:
			selected_index = int(selected_index)
			if selected_index not in list_num_files:
				print("Неверный номер файла.")
				return False

			selected_file = conf_files.get(selected_index)

		except ValueError:
			print("Пожалуйста, введите валидный номер.")
			return False


		if is_wireguard_running():
			for interface_name in get_wireguard_interface():
				if f"{interface_name}.conf" == selected_file:
					print("WireGuard активен")
					return True
				else:
					print("Найденные интерфейсы WireGuard:")
					for interface in get_wireguard_interface():
						print(interface)

					print()
					for interface_name in get_wireguard_interface():
						os.system(f"sudo wg-quick down '{directory}{interface_name}.conf'")
					print()
					os.system(f"wg-quick up '{directory}{selected_file}'")

					return True

		else:
			print("Нет активных конфигураций WireGuard\n")
			os.system(f"wg-quick up '{directory}{selected_file}'")
			return True


	if fl.lower() == "y":
		if is_wireguard_running():
			for interface_name in get_wireguard_interface():
				os.system(f"wg-quick down '{directory}{interface_name}.conf'")
			return True
		else:
			print("Нет активных конфигураций WireGuard")
			return True


if __name__  == "__main__":
	main()
	input("\nEnter для закрытия...")
