#!/bin/bash

N=$(zenity --entry --title="Введите название архива" --text="Введите имя архива (без .zip):")
if [ -n "$N" ]; then
    zip -9 "${N}.zip" $@
else
    notify-send -a 'compress files' 'no archive name'
fi
